union KnownFor = Movie | TV

type People {
  adult: Boolean!
  gender: Int
  id: ID!
  known_for_department: String!
  name: String!
  original_name: String!
  popularity: Float
  profile_path: String
  known_for: [KnownFor]
}
