enum TimePeriod {
  WEEK
  DAY
}

type Query {
  getPopularPeoples(page: Int!): [People]
  getPersonDetail(id: ID!): Person
  getPersonImages(id: ID!): [Image]
  getPersonCredits(id: ID!): Credit
  getTrendingPeoples(time: TimePeriod!): [People]
}
