enum TimePeriod {
  WEEK
  DAY
}

type Query {
  getPopularPeoples(page: Int!): [People]
  getPersonDetail(id: ID!): Person
  getPersonImages(id: ID!): [Image]
  getPersonMovieCredits(id: ID!): [Movie]
  getPersonTvCredits(id: ID!): [TV]
  getTrendingPeoples(time: TimePeriod!): [People]
}
