version: "3"
services:
  server:
    image: <docker-image-name>
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - redis
    command: npm run dev # Command to run the server, no need for ./server prefix

  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - 6379:6379
      - 8001:8001 # Optional: Web UI port for Redis Stack (if using Redis Stack)
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
