enum Time_Period {
  WEEK
  DAY
}

type Query {
  getAiringTodayTvShows(page: Int!): [TV]
  getOnTheAirTvShows(page: Int!): [TV]
  getPopularTvShows(page: Int!): [TV]
  getTopRatedTvShows(page: Int!): [TV]
  getTvShowDetails(id: ID!): TV_Show_Detail
  getTvShowSeason(id: ID!, season: ID!): Season
  getTvShowRecommendation(id: ID!, page: Int!): [TV]
  getTvShowSimilar(id: ID!, page: Int!): [TV]
  getTvShowImage(id: ID!): [Image]
  getTvShowReviews(id: ID!): [Review]
  getTrendingTvShows(time: Time_Period!): [TV]
}
