enum TimePeriod {
  WEEK
  DAY
}

type Query {
  getNowPlayingMovies(page: Int!): [Movie]
  getPopularMovies(page: Int!): [Movie]
  getTopRatedMovies(page: Int!): [Movie]
  getUpcomingMovies(page: Int!): [Movie]
  getMovie(id: ID!): MovieDetail
  getMovieRecommendations(page: Int!, id: ID!): [Movie]
  getSimilarMovies(page: Int!, id: ID!): [Movie]
  getMovieImages(id: ID!): [Image]
  getMovieReviews(id: ID!): [Review]
  getTrendingMovies(time: TimePeriod!): [Movie]
}
