type Mutation {
  deleteWatchlistMovie(id: Int!): Boolean!
  deleteWatchlistTvShow(id: Int!, season: Int!): Boolean!
  postWatchlistMovie(id: Int!): Boolean!
  postWatchlistTvShow(id: Int!, season: Int!): Boolean!
}
