type Mutation {
  deleteWatchlistMovie(id: Int!): Response!
  deleteWatchlistTvShow(id: Int!, season: Int!): Response!
  postWatchlistMovie(id: Int!): Response!
  postWatchlistTvShow(id: Int!, season: Int!): Response!
}
