type Mutation {
  deleteWatchlistMovie(id: ID!): Response!
  deleteWatchlistTvShow(id: ID!, season: ID!): Response!
  postWatchlistMovie(id: ID!): Response!
  postWatchlistTvShow(id: ID!, season: ID!): Response!
}
