type Query {
  getWatchlistMovies(page: Int): [MovieDetail!]
  getWatchlistTvShows(page: Int): [WatchlistTv!]
  checkMovieInWatchlist(id: ID!): Response!
  checkTvShowInWatchlist(id: ID!, season: ID!): Response!
}

type Response {
  id: ID!
  bool: Boolean!
}

type WatchlistTv {
  id: ID!
  air_date: String
  name: String!
  overview: String
  popularity: Float
  poster_path: String
  season_number: String
  vote_average: Float
}
