type Query {
  getWatchlistMovies: [MovieDetail!]
  getWatchlistTvShows: [Season!]
  checkMovieInWatchlist(id: Int!): Response!
  checkTvShowInWatchlist(id: Int!, season: Int!): Response!
}

type Response {
  id: ID!
  bool: Boolean!
}
