enum TimePeriod {
  Week
  Day
}

type Query {
  getNowPlayingMovies(page: Int!): [Movie]
  getPopularMovies(page: Int!): [Movie]
  getTopRatedMovies(page: Int!): [Movie]
  getUpcomingMovies(page: Int!): [Movie]
  getMovie(id: ID!): MovieDetail
  getMovieRecommendations(page: Int!, id: Int!): [Movie]
  getSimilarMovies(page: Int!, id: Int!): [Movie]
  getMovieImages(id: Int!): [Image]
  getMovieReviews(id: Int!): [MovieReview]
  getTrendingMovies(time: TimePeriod!): [Movie]
}
