type Review {
  author: String
  author_details: AuthorDetails
  content: String
  created_at: String
  id: String
  updated_at: String
  url: String
}

type AuthorDetails {
  name: String
  username: String
  avatar_path: String
  rating: Float
}
